### ISSUE TITLE
updated homebridge-hue, now i ve got npmjs timeout 5s, homebridge bootloop

### ISSUE THREAD

**Issue by Dominik-1980** [ebaauw/homebridge-hue#846]
#### Issue

updated homebridge-hue to latest, now i ve got npmjs timeout 5s, homebridge bootloop
#### Log Messages

```
```
Error: registry.npmjs.org: timeout after 5 seconds
    at newError (/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/HttpClient.js:26:10)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/HttpClient.js:331:25)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.emitRequestTimeout (_http_client.js:784:9)
    at Object.onceWrapper (events.js:421:28)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

**Comment by ebaauw** [comment]
Please attach a debug log file.

**Comment by DrDoom666** [comment]
How do i get this?

**Comment by ebaauw** [comment]
See https://github.com/ebaauw/homebridge-hue#debug-log-file

**Comment by DrDoom666** [comment]
I have changed the config.json timeout from 5 to 25, but the error is still there showing 5s timeout

**Comment by DrDoom666** [comment]
What can I say... I uninstalled the homebridge-hue plugin and deleted the config in the config.json.
Now, i reinstalled it and copy and paste my hue config. Now it works like a charm without any errors... :-)

**Comment by ebaauw** [comment]
The NPM registry seems slow lately, maybe `npm` didn't install the latest version at first?

v0.12.6 has issues running on NodeJS v12.x, but v0.12.7 should be OK.

**Comment by DrDoom666** [comment]
I am on node.js 14.15.1
and npm 6.14.8

**Comment by DrDoom666** [comment]
It took me one hour to set up my complex automations again with many zigbee sensors, dependencies and Shortcuts.
Homekit kicked everything out and put it in the standard room after i got homebridge running again.
Is there any possibility to keep this settings in case something goes wrong in the future?

**Comment by mtressl** [comment]
Same issue here, I am annoyed AF. Can feel your pain @DrDoom666.

For reference, the log entries when the hue plugin makes the crap and send everything south:
`[12/5/2020, 11:41:22 PM] Error: registry.npmjs.org: timeout after 5 seconds
    at newError (/homebridge/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/HttpClient.js:26:10)
    at ClientRequest.<anonymous> (/homebridge/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/HttpClient.js:331:25)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.emitRequestTimeout (_http_client.js:784:9)
    at Object.onceWrapper (events.js:421:28)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)`

**Comment by DrDoom666** [comment]
You can try to deinstall homebridge-hue, delete the settings in config.json, restart the server, install homebridge-hue again and copy and paste the settings back in config.json.
For me it worked.

**Comment by mtressl** [comment]
Yeah, I know. But then I'd need to fix the room configs again, and the scenes, and my 20 Alexa routines as well.

@ebaauw : how can I force an full reinstall from npm so I get the latest versions?

**Comment by mtressl** [comment]
Did a downgrade to v0.12.4 and back to v0.12.7 and now it seems fine.

**Comment by ebaauw** [comment]
**Warning** If you start Homebridge without Homebridge Hue, HomeKit will delete all accessories exposed by Homebridge Hue.  They'll re-appear when you next run Homebridge with Homebridge Hue, but you'll have lost all associations with HomeKit rooms, groups, scenes, automations.

To uninstall Homebridge Hue: `sudo npm -g un homebridge-hue`.

To install a particular version (other than `latest`): `sudo npm -g i homebridge-hue@0.12.4`

**Comment by ebaauw** [comment]
If contacting the NPM registry fails, Homebridge exits due an unchecked error.   The NPM registry isn't the most stable service on the Internet, so the error will be intermittent.

Homebridge Hue v0.12.8 should fix this (and some more possible unchecked errors).

**Comment by mtressl** [comment]
Hi @ebaauw 
ist the following error also related to NPM timeouts? It came up with one of the versions published yesterday and is still present in v0.12.8:

`[12/6/2020, 10:54:32 AM] [Philips Hue & deCONZ (ZigBee)] request 14405: GET /sensors
[12/6/2020, 10:54:32 AM] [Philips Hue & deCONZ (ZigBee)] 192.168.1.144: timeout after 5 seconds
[12/6/2020, 10:54:32 AM] [Philips Hue & deCONZ (ZigBee)] RaspBee-II-GW: gateway request 14405: get /sensors
[12/6/2020, 10:54:32 AM] [Philips Hue & deCONZ (ZigBee)] RaspBee-II-GW: gateway communication error: 192.168.1.144: timeout after 5 seconds
[12/6/2020, 10:54:32 AM] [Philips Hue & deCONZ (ZigBee)] RaspBee-II-GW: heartbeat error: 192.168.1.144: timeout after 5 seconds`

I know it is related to deCONZ and RaspBee-II. No clue why, but deCONZ seems to run stable.

**Comment by ebaauw** [comment]
Not related.

I take it Homebridge and Homebridge Hue continue to run?

**Comment by mtressl** [comment]
Yes they keep running.
But it's three lines of yellow warnings, and the last line is red which makes me worry.

![image](https://user-images.githubusercontent.com/1140154/101277903-f7bf8a00-37b7-11eb-807e-1def48729bbb.png)

**Comment by mtressl** [comment]
From a REST client get /lights and get /sensors works fine, no timeouts.

**Comment by ebaauw** [comment]
> But it's three lines of yellow warnings, and the last line is red which makes me worry.

I'll make the red line yellow in the next version and double check the amount of messages.

> From a REST client get /lights and get /sensors works fine, no timeouts.

Do you the timeout continuously in the log, or only rarely?  There's still an issue that the deCONZ REST API plugin freezes for a couple of seconds while saving the database, so a `timeout` of 5 seconds might be a bit challenging.  Also, I'd recommend running Homebridge and deCONZ on the same server, to cut out any network overhead between the two of them.

**Comment by mtressl** [comment]
Homebridge and deCONZ are on the same server.
Both running in their own Docker (I think my setup is pretty similar to yours, with Raspberry and RaspBee-II).

The timeouts are random: last two happened 11:34 AM (from screenshot above, plus another one right before), since then (now it's 12:06 PM) nothing happened.

Will try a more generous `timeout` now.

**Comment by ebaauw** [comment]
I don't do Docker.

**Comment by mtressl** [comment]
> I don't do Docker.

okay!

**Comment by ebaauw** [comment]
Messages sanitised in v0.10.12.
